disabled_rules: # rule identifiers to exclude from running
#  - colon
#  - comma
#  - control_statement
#  - file_length
#  - force_cast
#  - force_try
#  - function_body_length
#  - leading_whitespace
#  - line_length
#  - nesting
#  - operator_whitespace
#  - opening_brace
#  - return_arrow_whitespace
#  - statement_position
#  - todo
#  - trailing_newline
#  - trailing_semicolon
  - trailing_whitespace
#  - type_body_length
  - type_name
  - valid_docs
  - variable_name
  - variable_name_min_length
#  - variable_name_max_length
excluded: # paths to ignore during linting. overridden by `included`.
  - Carthage
  - Pods
  - fastlane
  - XLProjectName/Helpers/R-Swift/R.generated.swift
# parameterized rules can be customized from this configuration file
file_length:
  - 700
  - 2000
line_length:
  - 1000
  - 12000
# parameterized rules are first parameterized as a warning level, then error level.
function_body_length:
  - 50 # warning
  - 100 # error
type_body_length:
  - 700 # warning
  - 900 # error
identifier_name:
  max_length:
  - 55 # warning
  - 60 # error
  excluded:
    - url
cyclomatic_complexity:
  - 10 # warning
  - 50 # error
function_parameter_count:
  - 8  # warning
  - 11 # error
